name: Build and test

on:
  push:
  pull_request:

jobs:
  ocaml-test:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - 4.08.1
          - 4.14.0

    name: Ocaml tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use ocaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: opam install . --deps-only --with-test -v

      - name: Build
        run: opam exec -- make build

      - name: Run tests
        run: opam exec -- dune runtest --instrument-with bisect_ppx --force

      - run: opam exec -- bisect-ppx-report send-to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
