name: Build and test

on:
  push:
  pull_request:

jobs:
  ocaml-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ocaml-compiler: 4.08.1
            publish-docs: false
          - ocaml-compiler: 4.14.0
            publish-docs: true

    name: Ocaml tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use ocaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: opam install . --deps-only --with-test --with-doc -v

      - name: Build
        run: opam exec -- make build

      - name: Build Docs
        run: opam exec -- make doc

      - name: Run tests
        run: opam exec -- dune runtest --instrument-with bisect_ppx --force

      - run: opam exec -- bisect-ppx-report send-to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref_name == 'master' && matrix.publish-docs == true }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/default/_doc/_html/
          publish_branch: gh-pages
